### PR TITLE
v0.9.2

### PR DESCRIPTION
**Pull request by ealter**
This bumps the version to include #76

### CODE REVIEW

**Comment by ealter** [comment]
@dnephin when this is merged, can you tag it with git?

**Comment by dnephin** [comment]
Will do. I've got a couple things to merge first, then I'll do a release. I hope to get to it tomorrow.

**Comment by dnephin** [comment]
I merged #77 so i'm going to bump to 0.10.0 instead and update the release notes.

**Comment by dnephin** [comment]
https://pypi.python.org/pypi/PyStaticConfiguration/0.10.0

Note there is a breaking change in this release with #77

**Pull request closed without merging**
