### PR TITLE
Update version to 0.11.0

### PR DESCRIPTION
**Pull request by ymilki**
Changes since 0.10.5
* Dropped py2 support, added more py3 support
* Added Type annotations

Note: Needs a tag and pypi release too

### CODE REVIEW

**Comment by ymilki** [comment]
@dnephin actually, since we've dropped py2, would you prefer a major version bump?

**Review by dnephin — APPROVED** [review]
This seems good to me. It's still technically pre-1.0, and the versions removed are EOL.

**Comment by dnephin** [comment]
Does this still need to get uploaded to pypi? I'll try tagging the commit and see if the automation still works.

**Comment by dnephin** [comment]
I guess there isn't any automation to release. Do you need it uploaded to pypi?

**Comment by ymilki** [comment]
Yes please, thanks!

**Pull request merged**
