### PR TITLE
Add typing annotations

### LINKED ISSUE #108: This library should have type annotations

### PR DESCRIPTION
**Pull request by ymilki**
Following mypy output, I typed each file until no errors were left.

Additionally added GHA for `tox -e mypy` to prevent regressions in PRs.

### Notes

There's a circular type dependency between `config.py` (`ConfigNamespace`) and `proxy.py` (`ValueProxy`) which is guarded by `TYPE_CHECKING`.

While I don't explicitly test for py3.10, `Protocol` was moved from `typing-extensions` to `typing` so there's a version guard for the `Protocol` import.

In `statticonfig/loader`, there are many `Comparator`s using the `IComparator` interface. Normally, I would turn `IComparator` into a `Protocol`, but one of the classes adds a default keyword arg to `__init__` which makes it different. To facilitate typing, I opted to make the inheritance explicit instead.

Closes #108

### CODE REVIEW

**Comment by ymilki** [comment]
Ping @benbariteau @matthewess

**Comment by ymilki** [comment]
Ping @dnephin.

Final commit marks the package as typed.

**Review by matthewess — APPROVED** [review]
I thought I already gave this a shipit, my bad!

**Review by dnephin — APPROVED** [review]
Awesome!

**Pull request merged**
