### PR TITLE
Update version to 0.11.1

### PR DESCRIPTION
**Pull request by ymilki**
Changes since 0.11.0:

* Fixed type annotation for a parameter #115
* (WIP) Narrow type definition for Readers and Getters #117
* Fixed type annotations for a class variable #118 
* Add `typing-extensions` to install requires #119 

Action Items:
- [x] Merge new PRs
- [ ] Tag merge commit after merging to master.

### CODE REVIEW

**Review by jvperrin — COMMENTED** [review]
Somewhat of a side note, but before this is released could you please add into the package that it now depends on `typing-extensions` being installed? Currently if you try to install and use this package it fails with this error:
```
jvperrin:~/tmp $ virtualenv -p python3.7 venv
created virtual environment CPython3.7.13.final.0-64 in 381ms
  creator CPython3Posix(dest=/nail/home/jvperrin/tmp/venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/nail/home/jvperrin/.local/share/virtualenv)
    added seed packages: pip==22.2.2, setuptools==60.10.0, wheel==0.37.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

jvperrin:~/tmp $ venv/bin/pip install pystaticconfiguration
Looking in indexes: http://169.254.255.254:20641/jammy/simple/
Collecting pystaticconfiguration
  Using cached http://169.254.255.254:20641/f/jammy/PyStaticConfiguration-0.11.0-py3-none-any.whl (27 kB)
Installing collected packages: pystaticconfiguration
Successfully installed pystaticconfiguration-0.11.0

jvperrin:~/tmp $ venv/bin/python3
Python 3.7.13 (default, Apr 24 2022, 01:06:43)
[GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import staticconf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nail/home/jvperrin/tmp/venv/lib/python3.7/site-packages/staticconf/__init__.py", line 1, in <module>
    from . import config  # noqa: F401
  File "/nail/home/jvperrin/tmp/venv/lib/python3.7/site-packages/staticconf/config.py", line 40, in <module>
    from typing_extensions import Protocol
ModuleNotFoundError: No module named 'typing_extensions'
```

**Comment by ymilki** [comment]
Thanks @jvperrin. I also have another PR to narrow a type in #117 that I'd like to include.

**Comment by dnephin** [comment]
Is this ready now that we've merged the other PRs?

**Comment by ymilki** [comment]
@dnephin yup, ready for a patch version.

**Review by dnephin — APPROVED** [review]

**Pull request merged**
